language: java
jdk:
  - oraclejdk8
install:
  - mkdir -p /home/travis/wpilib/java/current/lib/
  - cp XbotCommonLib/lib/WPILib.jar /home/travis/wpilib/java/current/lib/
  - cp XbotCommonLib/lib/NetworkTables.jar /home/travis/wpilib/java/current/lib/
script:
  - cd XbotCommonLib && ant jar
  - cd ../CompetitionTemplate && ant jar
  - ant demo

